### ISSUE TITLE
Missing Compat in dependencies

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaAudio/LibSndFile.jl#19]
The BinDeps build.jl file tries to load Compat but Compat is not in the REQUIRE file.

**Comment by haberdashPI** [comment]
This now leads to an error when trying to build LibSndFile on the latest Julia (1.2). Would you accept a PR to added this dependency, as a temporary fix to this issue, until #20 is solved?

**Comment by haberdashPI** [comment]
I looked into this a bit, just to see, and it was a bit of a mess, at least on my machine (boiling down to some problem building `Homebrew`). I don't see a temporary fix, at least for me purposes.

**Comment by ssfrr** [comment]
I haven't been following the latest BinaryBuilder/Yggdrasil/Artifacts developments so not sure what the latest-and-greatest approach for distributing binaries is. I definitely don't have a problem adding Compat as a dependency, but @haberdashPI are you saying that's not the only issue?

I'm also happy to drop pre-1.0 support if that makes it easier to get things working on 1.2/1.3.

**Comment by haberdashPI** [comment]
Yes, that seems to be the cae, but I can't be certain. I haven't investigated fully why exactly I couldn't get things to work. The problem I had was that Homebrew doesn't currently build on mac . osx, and so I couldn't install the binary dependencies for LibSndFile.jl. I haven't hunted down why exactly that is or how things would break on other systems, because it seems like the general goal is move away from things like Homebrew.jl and towards BinaryBuilder.

**Comment by danmackinlay** [comment]
In the interim it sounds like we should require Julia<1.2 for LibSndFile. Should that patch be our focus here, if more substantial changes are negated by #20 ?

**Comment by ssfrr** [comment]
Looks like #24 is building successfully on linux and OSX (Appveyor is being slow, so we'll see). Does that resolve people's issues for now?

**Comment by ssfrr** [comment]
Seems to be good to go, and will be released in [version 2.2.0](https://github.com/JuliaRegistries/General/pull/5645)
