### ISSUE TITLE
Package the libsndfile dependency  for BB

### ISSUE THREAD

**Issue by ViralBShah** [JuliaAudio/LibSndFile.jl#20]
It would be nice to package the underlying libsndfile dependency for BB. I opened an issue at Yggdrasil as well.

https://github.com/JuliaPackaging/Yggdrasil/issues/107

I also think this is a better way to address #19.

**Comment by haberdashPI** [comment]
As noted in JuliaPackaging/Yggdrasil#107, I'm working on getting libsndfile setup in BB. I'm posting this here so @ssfrr will also know I'm working on this. My goal, once libsndfile is available on BB, is to close this issue so that `LibSndFile.jl` is usable on recent julia releases.

**Comment by haberdashPI** [comment]
Now that I've closed JuliasPackaging/Yggdrasil/#107 I'm not entirely sure about the workflow to make use of the auto-generated packages from [JuliaBinaryWrappers](https://github.com/JuliaBinaryWrappers?utf8=%E2%9C%93&q=&type=&language=). 

If I understand correctly I could just use `]add https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl` to include the binary during development, but this couldn't be published to the General registry until it knows about libsndfile_jl. Right?

**Comment by danmackinlay** [comment]
And does that in fact get us Julia 1.2 support or would LibSndFile still be dead for julia 1.2?

**Comment by ssfrr** [comment]
> If I understand correctly I could just use `]add https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl` to include the binary during development, but this couldn't be published to the General registry until it knows about libsndfile_jl. Right?

Once we've verified that the library that Yggdrasil is building is good, is the next step to register `libsndfile_jll.jl` as a package in General, so then LibSndFile.jl can depend on it?

**Comment by haberdashPI** [comment]
@danmackinlay: I have not been able to get LibSndFile working in Julia 1.0-1.2. My PR was one approach to get it working, but it only works for 1.3.

@ssfrr: I suppose that might be. That seems reasonable, but I'm not clear on what the expected process for registration of *.jll packages is. That WIP blog post I linked to doesn't seem to address those questions.

**Comment by ssfrr** [comment]
oh, nvm, looks like it's already registered! Though it doesn't seem installable:

```
pkg> add libsndfile_jll
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package libsndfile_jll [5bf562c0]:
 libsndfile_jll [5bf562c0] log:
 ├─possible versions are: 1.0.28 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 1.0.28
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

**Comment by ssfrr** [comment]
oh, heh, I'm no Julia 1.2, which probably won't work... Sorry for the noise.

**Comment by staticfloat** [comment]
Yes, that's correct. The whole `JuliaBinaryWrappers` organization is auto-generated from build scripts (most of which live in [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil), our community buildtree).  If you want more details on the changes that JLL packages bring, read [this blog post](https://julialang.org/blog/2019/11/artifacts), or the [Pkg Artifacts documentation](https://julialang.github.io/Pkg.jl/dev/artifacts/) for more nitty-gritty details.  For even MORE, you can take a look at the changes carried on the branches pointed to by [this test repository](https://github.com/staticfloat/GtkArtifactTest) which uses only Artifacts to get you a working `Gtk.jl` on all three major platforms; that can help you to understand the kinds of changes necessary to switch over to a JLL package instead of BinaryProvider, and how Artifacts can be used by your own packages.

**Comment by ssfrr** [comment]
The `libsndfile_jll` package seems to be working great. Thanks all!
